global proc FilePathLocator() {};

string $LocatorInfo = `whatIs FilePathLocator`;
string $filePath = `substring $LocatorInfo 25 999`;
string $pluginDir = `dirname $filePath`;

string $pythonCmd = "import sys;";
$pythonCmd += "sys.path.append('" + $pluginDir + "');";
$pythonCmd += "import install;";
$pythonCmd += "import importlib;";
$pythonCmd += "importlib.reload(install);";
$pythonCmd += "install.Install()";

python($pythonCmd);